### ISSUE TITLE
미완된 작업 리스트업

### ISSUE THREAD

**Issue by piggmme** [Climeeting/climeet-fe#122]
@SUPER0214T 
여기 이슈에 댓글로 미완된 작업 작성해주시면 감사하겠습니다!

**Comment by SUPER0214T** [comment]
파티 생성 시에 대표 사진 등록하는 기능

**Comment by SUPER0214T** [comment]
파티 수정 시에 참가자 여부에 따라 수정 가능한 항목 제한하는 기능 추가

**Comment by SUPER0214T** [comment]
파티 상세 페이지에서 파티 수정 버튼의 기능 추가

**Comment by piggmme** [comment]
홈화면
- 검색 필터 칩
- 마감제거
- 날짜 필터링 정상 동작 확인 필요
- 파티 썸네일 ui

파티 디테일
- 파티 썸네일
- 암장 주소 복사
- 실력분포 그래프 색상

유저 페이지
- 유저 피드 영역
- 정보 수정 실패시 안내 문구
- 글자수 카운트 ui
- 실력 선택 bottom sheet 로 수정필요
