### ISSUE TITLE
PWA 설정

### ISSUE THREAD

**Issue by piggmme** [Climeeting/climeet-fe#2]
- [ ] [vite-plugin-pwa](https://vite-pwa-org.netlify.app/) 설치
- [ ] ios test
- [ ] android test

**Comment by SUPER0214T** [comment]
## 이미지, manifest 생성 방법

https://favicon.io/favicon-converter/ 에서 이미지를 업로드하면 크기별로 다운받고 manifest, link를 생성할 수 있습니다.

**Comment by SUPER0214T** [comment]
## 안드로이드 테스트

안드로이드 기기의 삼성 인터넷, 크롬 브라우저의 상단에 다운로드 버튼이 생성되는 것 확인하였습니다.

**Comment by SUPER0214T** [comment]
display: "fullscreen" 설정시 안드로이드에서 상단바가 검은색으로 표시되어 완벽한 전체 화면이 아니게 되는 문제가 있습니다.
