### ISSUE TITLE
파티 생성 스텝 Scroll Picker 구현

### ISSUE THREAD

**Issue by SUPER0214T** [Climeeting/climeet-fe#77]
![image](https://github.com/Climeeting/climeet-fe/assets/83449231/2bac0706-ea61-44d8-be13-5f49696ff469)

**Comment by piggmme** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-snap-type
이거 사용하시면 스크롤이 칸에 맞춰서 탁탁 넘어가져서 조금더 모바일 친화적이에요!
