### ISSUE TITLE
유저 위치 정보 가져오기

### ISSUE THREAD

**Issue by piggmme** [Climeeting/climeet-fe#8]
https://developer.mozilla.org/ko/docs/Web/API/Geolocation_API
- 디바이스의 위치 정보를 가져오는 플로우가 어떤지 확인 필요
- PWA 환경에서는 어떻게 동작하는지도 확인 필요
- 각자 자료 조사 후 여기에다가 기록 남기기!!

**Comment by SUPER0214T** [comment]
## 디바이스의 위치 정보 가져오기

Geolocation API를 사용하여 위도, 경도를 알아낸 후 Kakao 지도 API의 [kakao.maps.services.Geocoder](https://apis.map.kakao.com/web/documentation/#services_Geocoder)를 사용하여 현재 위도, 경도에 대한 주소 정보를 얻을 수 있습니다.

또한, [OpenCage Geocoding API](https://opencagedata.com/)를 사용해서도 현재 주소 정보를 얻을 수 있습니다.

**Comment by piggmme** [comment]
- [Geolocation API](https://inpa.tistory.com/entry/JS-%F0%9F%93%9A-Geolocation-API%EB%A1%9C-%F0%9F%97%BA%EF%B8%8F-%EC%9C%84%EB%8F%84-%EA%B2%BD%EB%8F%84-%EC%96%BB%EA%B3%A0-%E2%9B%85-%EB%82%A0%EC%94%A8-%EC%98%A8%EB%8F%84-%EC%A0%95%EB%B3%B4%EB%A5%BC-%EC%96%BB%EC%96%B4%EC%98%A4%EA%B8%B0)
